SUBCATEGORIA_TO_CLASE = {
    "Alta de usuario": "ALTA/BAJA",
    "Alta de usuario RETACEO": "ALTA/BAJA",
    "Baja de usuario": "ALTA/BAJA",
    "Baja de usuario RETACEO": "ALTA/BAJA",
    "Cambio de contraseña": "ALTA/BAJA",
    "Desbloque de contraseña": "ALTA/BAJA",
    "Desbloqueo de contraseña Tiendas Franquicias": "ALTA/BAJA",
    "Creación de nuevos usuarios": "ALTA/BAJA",
    "Crear, eliminar y administrar cuentas de usuaios": "ALTA/BAJA",
    "Altas, bajas y cambios usuarios Active Directory": "ALTA/BAJA",
    "Altas, bajas y cambios usuarios red inalámbrica": "ALTA/BAJA",
    "Altas, bajas y cambios usuarios VPN C2S": "ALTA/BAJA",
    "Dar de alta credenciales de usuario": "ALTA/BAJA",
    "Dar de baja credenciales de usuario": "ALTA/BAJA",
    "Asignación, designación de roles": "ALTA/BAJA",
    "Asignar susbcripción a usuarios": "ALTA/BAJAL",
    "Incremento de tamaño de Buzón": "ALTA/BAJA",
    "Creación de tenant y/o subscripción": "ALTA/BAJA",
    "Crear de cuentas de usuario en Azure Active Directory": "ALTA/BAJA",
    "Activación del MFA": "ALTA/BAJA",
    "Asignación de acceso a carpeta compartida (lectura/escritura)": "ALTA/BAJA",
    "Creeación y modificación de usuario": "ALTA/BAJA",
    "Retiro de licencia": "ALTA/BAJA",
    "Asignación de acceso a carpeta compartida (lectura/escritura)": "ALTA/BAJA",
    "Configuración de permisos en archivos y directorios": "ALTA/BAJA",
    "Habilitación/Deshabilitación de políticas de seguridad para roles/usuarios": "ALTA/BAJA",
    "Reseteo de claves de usuario": "ALTA/BAJA",
    "Crear, modificar, eliminar usuarios no predeterminados": "ALTA/BAJA",
    "Crear, modificar, roles/usuarios/equipos en VCenter": "ALTA/BAJA",
    "Creación de usuarios": "ALTA/BAJA",
    "Perdida de acceso a Tenant Azure": "ALTA/BAJA",
    "Perdida de acceso a Tenant Google": "ALTA/BAJA",
    "Problemas de acceso al Tenant": "ALTA/BAJA",
    "Problemas de rendimiento en servicios": "ALTA/BAJA",
    "Configuración de reglas de acceso a recursos del Tenant": "ALTA/BAJA",
    "Creación Usuario": "ALTA/BAJA",
    "Modificación Usuario": "ALTA/BAJA",
    "Baja de Usuario": "ALTA/BAJA",
    "Creación/modificación usuarios (solo lectura)": "ALTA/BAJA",
    "Alta de usuario": "ALTA/BAJA",
    "Baja de Usuario": "ALTA/BAJA",
    "Modificación de usuario": "ALTA/BAJA",
    "Alta/baja/cambios usuarios de base de datos (ABC)": "ALTA/BAJA",
    "Actualización de Datos": "ALTA/BAJA",
    "Crear, eliminar, modificar listas Blancas/Negras": "ALTA/BAJA",
    "Eliminación de usuarios": "ALTA/BAJA",
    "Desbloqueo de usuario": "ALTA/BAJA",
    "Deshabilitación/Eliminación de ambientes": "ALTA/BAJA",
}